export const SET_INPUT_FILENAME = 'SET_INPUT_FILENAME';
export const READ_EXCEL = 'READ_EXCEL';
export const SET_INPUT_FILE = 'SET_INPUT_FILE';
export const SET_LOADING = 'SET_LOADING';
export const SET_SHEET_NAME = 'SET_SHEET_NAME';
export const SET_TABLE_DATA = 'SET_TABLE_DATA';
export const SET_SELECTED_LABELS = 'SET_SELECTED_LABELS';
